name: Create release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true
        default: '1.0.0'

jobs:
  release:
    permissions:
      contents: 'write'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: 'Create release'
      uses: 'ncipollo/release-action@v1'
      with:
        allowUpdates: true
        makeLatest: true
        name: 'MyApp-${{ github.event.inputs.version }}'
        tag: '${{ github.event.inputs.version }}'

