name: Bump version and push tag
on: 
  workflow_dispatch:
    inputs:
      version-bump:
        description: 'Version bump (major, minor, patch)' 
        required: true
        default: 'patch'

jobs:
  build:
    name: Bump version and push tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # this is required for "git describe" to work correctly

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ github.event.inputs.version-bump }}
