name: Create release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        # Add your commands for setting up the environment here

    - name: Build
      run: |
        # Add your commands for building your project here

    - name: Test
      run: |
        # Add your commands for testing your project here

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.version }}
        release_name: Release ${{ github.event.inputs.version }}
        body: |
          Changes in this Release
          - Enter changes here
